In [7]:
import numpy as np

In [2]:
#create a array
a=[1,2,3,4,5]

arr= np.array(a)

In [9]:
print(arr)

[[1 2 3 4 5]]


In [5]:
arr.ndim

1

In [6]:
arr.shape

(5,)

In [7]:
#create a array
a=[[1,2,3,4,5]]

arr= np.array(a)

In [8]:
arr

array([[1, 2, 3, 4, 5]])

In [9]:
a = np.random.choice(5,6)
a

array([2, 4, 3, 4, 2, 2])

In [1]:
# write  a program find the non zero values