In [3]:
import numpy as np
print(np.__version__)

1.23.5


In [10]:
#1Dimensional and 2Dimensional
#create 0D array
a1=np.array([50])
print(a1)
#create 1D array
a=np.array([1,2,3])
print((a))
#create 2D array
b=np.array([[1,5,6],[7,8,89]])
print(b)
#create 3D array
b1=np.array([[[1,5,8],[4,5,9]],[[4,5,6],[5,6,8]]])
print(b1)

[50]
[1 2 3]
[[ 1  5  6]
 [ 7  8 89]]
[[[1 5 8]
  [4 5 9]]

 [[4 5 6]
  [5 6 8]]]


In [10]:
# using python in numpy 
my_list=[1,5,7,8,9]
my_array=np.array(my_list)
#Accessing elements of the numpy array
print(my_array[0])
print(my_array[4])

1
9


In [12]:
#Example adding to array
arr1=np.array([1,5,6])
arr2=np.array([5,6,9])
arr_sum=arr1+arr2
print(arr_sum)

[ 6 11 15]


In [18]:
# sequential array and matrices array use in NumPy
a=np.array([1,5,6,7])
print(a)
b=np.array([[7,5,6],[8,9,8],[1,2,3]])
print(b)
c=np.array([[8,5,6],[1,9,8],[1,1,3]])
arr_sum=b/c
print(arr_sum)

[1 5 6 7]
[[7 5 6]
 [8 9 8]
 [1 2 3]]
[[0.875 1.    1.   ]
 [8.    1.    1.   ]
 [1.    2.    1.   ]]


In [21]:
#Concatenate:is list which is made in array combine all the value in 1D array
arr1=np.array([1,5,6])
arr2=np.array([2,5,7])
arr3=np.array([1,5,8])
concatenate_arr=np.concatenate((arr1,arr2,arr3))
print(concatenate_arr)


[1 5 6 2 5 7 1 5 8]


In [7]:
arr_list=np.array([12,55,6])
arr_tuple=np.array((12,55,6))
arr_set=np.array({12,55,6})
print(arr_list,type(arr_list))
print(arr_tuple,type(arr_tuple))
print(arr_set,type(arr_set))

[12 55  6] <class 'numpy.ndarray'>
[12 55  6] <class 'numpy.ndarray'>
{12, 6, 55} <class 'numpy.ndarray'>
