In [1]:
import numpy as np 
import pandas as pd

In [2]:
# we can make series using -> dict, array or list , vector 


In [3]:
# array or list 

a  = np.arange(7,15)
a

array([ 7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
s = pd.Series(a)
s

0     7
1     8
2     9
3    10
4    11
5    12
6    13
7    14
dtype: int64

In [5]:
s = pd.Series(a, index=list('abcdefgh'))
s

a     7
b     8
c     9
d    10
e    11
f    12
g    13
h    14
dtype: int64

In [6]:
s['a']

7

In [7]:
s['e']

11

In [8]:
d = {'a':0,'b':5,'c':6}
st = pd.Series(d)
st

a    0
b    5
c    6
dtype: int64

In [9]:
sc  = pd.Series(5,index=list('abc'))
sc

a    5
b    5
c    5
dtype: int64

In [10]:
dt = np.random.randint(15,(5,3))
dt

ValueError: low >= high

In [11]:
sd = np.random.randint(4,2,3)
sd

ValueError: low >= high

In [12]:
sd = np.random.randint(0,15,15).reshape(3,5)
sd

array([[ 0,  5,  5, 12, 13],
       [13,  8,  2,  4,  9],
       [ 5, 13, 11, 12,  5]])

In [20]:
s = np.random.randint(0,15,size = (5,5))
s

array([[ 1,  9,  7,  5,  5],
       [ 0, 10,  4,  8,  3],
       [ 3,  0, 10,  7,  6],
       [ 2,  0, 13,  5,  8],
       [10, 10, 11,  1,  4]])

In [15]:
d = {'a':0,'b':5,'c':6}
st = pd.Series(d, index = ['a','g','b'])
st

a    0.0
g    NaN
b    5.0
dtype: float64

In [16]:
s

array([[ 6,  0,  6],
       [13,  4,  5],
       [ 8,  5,  8],
       [11,  5,  6],
       [ 6,  0,  7]])

In [17]:
# dataframe 
# array or list, dic, series, from another dataframe 

df = pd.DataFrame(s)
df

0  1  2
0   6  0  6
1  13  4  5
2   8  5  8
3  11  5  6
4   6  0  7

In [21]:
df = pd.DataFrame(s, columns=['Table1', 'Table2', 'Table3', 'Table4'])
df

ValueError: Shape of passed values is (5, 5), indices imply (5, 4)

In [23]:
df = pd.DataFrame(s, columns=['Table1', 'Table2', 'Table3', 'Table4', 'Table5'])
df

Table1  Table2  Table3  Table4  Table5
0       1       9       7       5       5
1       0      10       4       8       3
2       3       0      10       7       6
3       2       0      13       5       8
4      10      10      11       1       4

In [27]:
d = {
    'A' : [1,2,3,4,5],
    'B' : [5,6,7,8,4],
    'D' : [1,3,5,7,8]
}

df = pd.DataFrame(d, columns = ["A", 'C', 'D'])
df

A    C  D
0  1  NaN  1
1  2  NaN  3
2  3  NaN  5
3  4  NaN  7
4  5  NaN  8

In [30]:
df["A", 'D']

KeyError: ('A', 'D')

In [33]:
df[["A", 'D']]

A  D
0  1  1
1  2  3
2  3  5
3  4  7
4  5  8

In [34]:
q = [12,34,56,23,56]

In [36]:
d = {
    'a':3,'b':4,'c':4

}
print(d)
d['a'] = 10
print(d)

{'a': 3, 'b': 4, 'c': 4}
{'a': 10, 'b': 4, 'c': 4}


In [37]:
df['W'] = q

In [38]:
df

A    C  D   W
0  1  NaN  1  12
1  2  NaN  3  34
2  3  NaN  5  56
3  4  NaN  7  23
4  5  NaN  8  56

In [39]:
df[df['W'] == 56]

A    C  D   W
2  3  NaN  5  56
4  5  NaN  8  56

In [40]:
df.isna()

A     C      D      W
0  False  True  False  False
1  False  True  False  False
2  False  True  False  False
3  False  True  False  False
4  False  True  False  False

In [43]:
df.isna().sum()

A    0
C    5
D    0
W    0
dtype: int64

In [44]:
df.dropna()

Empty DataFrame
Columns: [A, C, D, W]
Index: []